package View;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lym
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        this.controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_Tabela = new javax.swing.JScrollPane();
        jTable_Tabela = new javax.swing.JTable();
        jButton_Agendar = new javax.swing.JButton();
        jScrollPane_Observacao = new javax.swing.JScrollPane();
        jTextAreaObservacao = new javax.swing.JTextArea();
        jComboBox_Servico = new javax.swing.JComboBox<>();
        jComboBox_Cliente = new javax.swing.JComboBox<>();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_Valor = new javax.swing.JTextField();
        jTextField_Data = new javax.swing.JTextField();
        jTextField_Hora = new javax.swing.JTextField();
        jLabel_ID = new javax.swing.JLabel();
        jLabel_Cliente = new javax.swing.JLabel();
        jLabel_Servico = new javax.swing.JLabel();
        jLabel_Valor = new javax.swing.JLabel();
        jLabel_Data = new javax.swing.JLabel();
        jLabel_Hora = new javax.swing.JLabel();
        jLabel_Observacao = new javax.swing.JLabel();
        jLabel_Agenda = new javax.swing.JLabel();
        jLabel_Opacity = new javax.swing.JLabel();
        jLabel_BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Tabela.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Tabela.setForeground(new java.awt.Color(0, 0, 0));
        jTable_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Matheus", "Barba", "30,00", "14/10/2024", "13:00", "Tirar tudo"},
                {"2", "Juliana", "Cabelo", "70,00", "01/03/2024", "15:00", "Cortar franja"},
                {"3", "Julia", "Completo", "100,00", "10/11/2024", "12:00", "Verificar"},
                {"4", "Ana", "Lavagem", "40,00", "11/10/2024", "11:00", null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jTable_Tabela.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_Tabela.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable_Tabela.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane_Tabela.setViewportView(jTable_Tabela);

        getContentPane().add(jScrollPane_Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 1120, 230));

        jButton_Agendar.setBackground(new java.awt.Color(51, 153, 0));
        jButton_Agendar.setFont(new java.awt.Font("P052", 1, 36)); // NOI18N
        jButton_Agendar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Agendar.setText("Agendar");
        jButton_Agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgendarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 190, 60));

        jScrollPane_Observacao.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane_Observacao.setForeground(new java.awt.Color(0, 0, 0));

        jTextAreaObservacao.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaObservacao.setColumns(20);
        jTextAreaObservacao.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaObservacao.setRows(5);
        jTextAreaObservacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane_Observacao.setViewportView(jTextAreaObservacao);

        getContentPane().add(jScrollPane_Observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 390, 360));

        jComboBox_Servico.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Servico.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Servico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_Servico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ServicoItemStateChanged(evt);
            }
        });
        jComboBox_Servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 340, 50));

        jComboBox_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Cliente.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 340, 50));

        jTextField_ID.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_ID.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_ID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 340, 50));

        jTextField_Valor.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Valor.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Valor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Valor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ValorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 340, 50));

        jTextField_Data.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Data.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Data.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Data.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 340, 50));

        jTextField_Hora.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Hora.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Hora.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Hora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 340, 50));

        jLabel_ID.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel_ID.setText("ID");
        getContentPane().add(jLabel_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel_Cliente.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel_Cliente.setText("Cliente");
        getContentPane().add(jLabel_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel_Servico.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel_Servico.setText("Serviço");
        getContentPane().add(jLabel_Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel_Valor.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel_Valor.setText("Valor R$");
        getContentPane().add(jLabel_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLabel_Data.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel_Data.setText("Data");
        getContentPane().add(jLabel_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        jLabel_Hora.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel_Hora.setText("Hora");
        getContentPane().add(jLabel_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        jLabel_Observacao.setFont(new java.awt.Font("P052", 1, 24)); // NOI18N
        jLabel_Observacao.setText("Observação");
        getContentPane().add(jLabel_Observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        jLabel_Agenda.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Agenda.setFont(new java.awt.Font("P052", 1, 48)); // NOI18N
        jLabel_Agenda.setText("Agenda");
        getContentPane().add(jLabel_Agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        jLabel_Opacity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Opacity_Dark_Agenda.png"))); // NOI18N
        getContentPane().add(jLabel_Opacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel_BackGround.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agenda_BackGround.png"))); // NOI18N
        getContentPane().add(jLabel_BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jComboBox_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ClienteActionPerformed

    private void jToggleButton_AgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton_AgendarActionPerformed

    private void jButton_AgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgendarActionPerformed
        this.controller.agendar();
    }//GEN-LAST:event_jButton_AgendarActionPerformed

    private void jComboBox_ServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ServicoActionPerformed
        this.controller.atualizaValor();
    }//GEN-LAST:event_jComboBox_ServicoActionPerformed

    private void jTextField_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ValorActionPerformed
    }//GEN-LAST:event_jTextField_ValorActionPerformed

    private void jComboBox_ServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ServicoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ServicoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Agendar;
    private javax.swing.JComboBox<String> jComboBox_Cliente;
    private javax.swing.JComboBox<String> jComboBox_Servico;
    private javax.swing.JLabel jLabel_Agenda;
    private javax.swing.JLabel jLabel_BackGround;
    private javax.swing.JLabel jLabel_Cliente;
    private javax.swing.JLabel jLabel_Data;
    private javax.swing.JLabel jLabel_Hora;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_Observacao;
    private javax.swing.JLabel jLabel_Opacity;
    private javax.swing.JLabel jLabel_Servico;
    private javax.swing.JLabel jLabel_Valor;
    private javax.swing.JScrollPane jScrollPane_Observacao;
    private javax.swing.JScrollPane jScrollPane_Tabela;
    private javax.swing.JTable jTable_Tabela;
    private javax.swing.JTextArea jTextAreaObservacao;
    private javax.swing.JTextField jTextField_Data;
    private javax.swing.JTextField jTextField_Hora;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Valor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServiço();
    }

    public JTable getjTable_Tabela() {
        return jTable_Tabela;
    }

    public void setjTable_Tabela(JTable jTable_Tabela) {
        this.jTable_Tabela = jTable_Tabela;
    }

    public JComboBox<String> getjComboBox_Cliente() {
        return jComboBox_Cliente;
    }

    public void setjComboBox_Cliente(JComboBox<String> jComboBox_Cliente) {
        this.jComboBox_Cliente = jComboBox_Cliente;
    }

    public JComboBox<String> getjComboBox_Servico() {
        return jComboBox_Servico;
    }

    public void setjComboBox_Servico(JComboBox<String> jComboBox_Servico) {
        this.jComboBox_Servico = jComboBox_Servico;
    }

    public JTextField getjTextField_Valor() {
        return jTextField_Valor;
    }

    public void setjTextField_Valor(JTextField jTextField_Valor) {
        this.jTextField_Valor = jTextField_Valor;
    }

    public JTextField getjTextField_Data() {
        return jTextField_Data;
    }

    public void setjTextField_Data(JTextField jTextField_Data) {
        this.jTextField_Data = jTextField_Data;
    }

    public JTextField getjTextField_Hora() {
        return jTextField_Hora;
    }

    public void setjTextField_Hora(JTextField jTextField_Hora) {
        this.jTextField_Hora = jTextField_Hora;
    }

    public JTextField getjTextField_ID() {
        return jTextField_ID;
    }

    public void setjTextField_ID(JTextField jTextField_ID) {
        this.jTextField_ID = jTextField_ID;
    }

    public JTextArea getjTextAreaObservacao() {
        return jTextAreaObservacao;
    }

    public void setjTextAreaObservacao(JTextArea jTextAreaObservacao) {
        this.jTextAreaObservacao = jTextAreaObservacao;
    }

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null,mensagem);
    }
    
}
