/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import Controller.LoginController;
import Model.DAO.*;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author lym
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
   private final LoginController controller;
    
    public Login() {
        initComponents();
        this.controller = new LoginController(this);
        BancoDAO.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jTextField_Username = new javax.swing.JTextField();
        jLabel_Text_Login = new javax.swing.JLabel();
        jLabel_Text_User = new javax.swing.JLabel();
        jLabel_Text_Password = new javax.swing.JLabel();
        jLabel_Fundo_Login = new javax.swing.JLabel();
        jLabel_Icon = new javax.swing.JLabel();
        jLabel_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 750, 200, 60));

        jPasswordField_Password.setFont(new java.awt.Font("P052", 0, 24)); // NOI18N
        jPasswordField_Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPasswordField_Password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPasswordField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 270, 40));

        jTextField_Username.setFont(new java.awt.Font("P052", 0, 24)); // NOI18N
        jTextField_Username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 270, 40));

        jLabel_Text_Login.setFont(new java.awt.Font("P052", 0, 24)); // NOI18N
        jLabel_Text_Login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Text_Login.setText("User");
        getContentPane().add(jLabel_Text_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, 60));

        jLabel_Text_User.setFont(new java.awt.Font("P052", 0, 24)); // NOI18N
        jLabel_Text_User.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Text_User.setText("Password");
        getContentPane().add(jLabel_Text_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, -1, 60));

        jLabel_Text_Password.setFont(new java.awt.Font("P052", 0, 48)); // NOI18N
        jLabel_Text_Password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Text_Password.setText("Barber Shop");
        getContentPane().add(jLabel_Text_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, 60));

        jLabel_Fundo_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Fundo_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fundo_Login.png"))); // NOI18N
        getContentPane().add(jLabel_Fundo_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        jLabel_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        getContentPane().add(jLabel_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Black Background Barbershop Peel and Stick Wallpaper(1).jpeg"))); // NOI18N
        getContentPane().add(jLabel_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PasswordActionPerformed

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.controller.botaoApertado();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_Background;
    private javax.swing.JLabel jLabel_Fundo_Login;
    private javax.swing.JLabel jLabel_Icon;
    private javax.swing.JLabel jLabel_Text_Login;
    private javax.swing.JLabel jLabel_Text_Password;
    private javax.swing.JLabel jLabel_Text_User;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null,mensagem);
    }

    public JPasswordField getjPasswordField_Password() {
        return jPasswordField_Password;
    }

    public void setjPasswordField_Password(JPasswordField jPasswordField_Password) {
        this.jPasswordField_Password = jPasswordField_Password;
    }

    public JTextField getjTextField_Username() {
        return jTextField_Username;
    }

    public void setjTextField_Username(JTextField jTextField_Username) {
        this.jTextField_Username = jTextField_Username;
    }
    
    
}
